### ISSUE TITLE
Bolt up-to-date official Firmware?

### ISSUE THREAD

**Issue by wisec** [tjclement/bolt#1]
Hey Tom! 
congrats for the project! 
I am having a lot of fun :)
It would be nice to have an up-to-date bolt firmware source code as I would like to play a bit with it. 
I see there's https://github.com/tjclement/ecsc23-badge/tree/main/fw/glitcher but I'm not sure it's the same firmware that's deployed on Bolt release.

Thanks!

**Comment by tjclement** [comment]
Hi @wisec, thanks for your kind words! Awesome to hear you like your Bolt.

Totally, bringing the latest fw in on this repo has been on the todo list for a few weeks now. I'll include it as-is for now to get you started, and hope to write some compilation and flashing instructions soon.

For your info now: you can get the Bolt in UF2 fw update mode either by calling Scope.update() from the python API, or by shorting the two round testpoint pads next to the USB connector during power-up.

Cheers!

**Comment by tjclement** [comment]
Just checked, and the main branch in the ecsc23 repo is up to date with the firmware flashed on Bolts before shipping. I've also added that codebase to this repo, where development will continue: https://github.com/tjclement/bolt/tree/main/firmware/bolt

Please let me know if you run into anything!

**Comment by wisec** [comment]
Super, thanks:)!

I was seeing the BOOTLOADER command missing but I can see it now on bolt repo.
Thanks & keep up!

**Comment by tjclement** [comment]
Ah, sharp comment! It turns out that the bootloader command commit had only been pushed to a private origin instead of the public ecsc23 repo. That's fixed now too. Thanks 👍
